[project]
name = "pubmed-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.8.0",
    "pymed>=0.8.9",
]
